package com.atsign.lockoutbingomod.core.init;

import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ItemInit {
    public static final DeferredRegister<Item> ITEMS;
    public static final RegistryObject<Item> ABSORPTION;
    public static final RegistryObject<Item> BAD_OMEN;
    public static final RegistryObject<Item> BREED_CHICKEN;
    public static final RegistryObject<Item> BREED_COW;
    public static final RegistryObject<Item> BREED_HOGLIN;
    public static final RegistryObject<Item> BREED_HORSE;
    public static final RegistryObject<Item> BREED_PIG;
    public static final RegistryObject<Item> BREED_SHEEP;
    public static final RegistryObject<Item> DIE_TO_ANVIL;
    public static final RegistryObject<Item> DIE_TO_BEE;
    public static final RegistryObject<Item> DIE_TO_CACTUS;
    public static final RegistryObject<Item> DIE_TO_FIREWORK;
    public static final RegistryObject<Item> DIE_TO_LLAMA;
    public static final RegistryObject<Item> DIE_TO_MAGIC;
    public static final RegistryObject<Item> DIE_TO_SWEET_BERRIES;
    public static final RegistryObject<Item> GLOWING;
    public static final RegistryObject<Item> HEIGHT_LIMIT;
    public static final RegistryObject<Item> JUMP_BOOST;
    public static final RegistryObject<Item> KILL_GHAST;
    public static final RegistryObject<Item> KILL_GUARDIAN;
    public static final RegistryObject<Item> KILL_PLAYER;
    public static final RegistryObject<Item> KILL_SILVERFISH;
    public static final RegistryObject<Item> KILL_SNOW_GOLEM;
    public static final RegistryObject<Item> KILL_STRAY;
    public static final RegistryObject<Item> KILL_STRAY_CYCLE;
    public static final RegistryObject<Item> KILL_WITCH;
    public static final RegistryObject<Item> KILL_ZOGLIN;
    public static final RegistryObject<Item> KILL_ZOMBIE_VILLAGER;
    public static final RegistryObject<Item> LEVITATION;
    public static final RegistryObject<Item> MINING_FATIGUE;
    public static final RegistryObject<Item> NAUSEA;
    public static final RegistryObject<Item> NO_CRAFTING_TABLE;
    public static final RegistryObject<Item> NO_DEATH;
    public static final RegistryObject<Item> NO_FALL_DAMAGE;
    public static final RegistryObject<Item> NO_FIRE;
    public static final RegistryObject<Item> NO_JUMP;
    public static final RegistryObject<Item> NO_OBSIDIAN;
    public static final RegistryObject<Item> NO_SEEDS;
    public static final RegistryObject<Item> NO_WATER;
    public static final RegistryObject<Item> STARVE;
    public static final RegistryObject<Item> TAME_CAT;
    public static final RegistryObject<Item> TAME_HORSE;
    public static final RegistryObject<Item> TAME_PARROT;
    public static final RegistryObject<Item> TAME_WOLF;
    public static final RegistryObject<Item> LEVEL_15;
    public static final RegistryObject<Item> Glow_Crimson_Sign;
    public static final RegistryObject<Item> Die_To_Falling_Stalactite;
    public static final RegistryObject<Item> NETHER_PORTAL;
    public static final RegistryObject<Item> ADVANCEMENTS_15;
    public static final RegistryObject<Item> ADVANCEMENTS_25;
    public static final RegistryObject<Item> ADVANCEMENTS_35;
    public static final RegistryObject<Item> STATUS_EFFECTS_3;
    public static final RegistryObject<Item> OF_ANYTHING_64;
    public static final RegistryObject<Item> STATUS_EFFECTS_6;
    public static final RegistryObject<Item> BREED_FOX;
    public static final RegistryObject<Item> BREED_GOAT;
    public static final RegistryObject<Item> BREED_OCELOT;
    public static final RegistryObject<Item> BREED_RABBIT;
    public static final RegistryObject<Item> BREED_STRIDER;
    public static final RegistryObject<Item> BREED_X;
    public static final RegistryObject<Item> DEAL_400_DAMAGE;
    public static final RegistryObject<Item> DIE_TO_ANCHOR;
    public static final RegistryObject<Item> DIE_TO_BED;
    public static final RegistryObject<Item> DIE_TO_GOLEM;
    public static final RegistryObject<Item> DIE_TO_VINES;
    public static final RegistryObject<Item> EAT_X_UNIQUE;
    public static final RegistryObject<Item> ENRAGE_ZOMBIE_PIGLIN;
    public static final RegistryObject<Item> KILL_100_MOBS;
    public static final RegistryObject<Item> KILL_BEE_CYCLE;
    public static final RegistryObject<Item> KILL_BLUE_SHEEP;
    public static final RegistryObject<Item> KILL_CAVE_SPIDER_CYCLE;
    public static final RegistryObject<Item> KILL_CYAN_SHEEP;
    public static final RegistryObject<Item> KILL_DROWNED;
    public static final RegistryObject<Item> KILL_ELDER_GUARDIAN;
    public static final RegistryObject<Item> KILL_ENDERMITE;
    public static final RegistryObject<Item> KILL_ENDERMITE_CYCLE;
    public static final RegistryObject<Item> KILL_GREEN_SHEEP;
    public static final RegistryObject<Item> KILL_HUSK;
    public static final RegistryObject<Item> KILL_LIGHT_BLUE_SHEEP;
    public static final RegistryObject<Item> KILL_LIME_SHEEP;
    public static final RegistryObject<Item> KILL_MAGENTA_SHEEP;
    public static final RegistryObject<Item> KILL_ORANGE_SHEEP;
    public static final RegistryObject<Item> KILL_PINK_SHEEP;
    public static final RegistryObject<Item> KILL_PURPLE_SHEEP;
    public static final RegistryObject<Item> KILL_RED_SHEEP;
    public static final RegistryObject<Item> KILL_SILVERFISH_CYCLE;
    public static final RegistryObject<Item> KILL_SPIDER_CYCLE;
    public static final RegistryObject<Item> KILL_WITHER_SKELETON;
    public static final RegistryObject<Item> KILL_X_UNIQUE;
    public static final RegistryObject<Item> KILL_YELLOW_SHEEP;
    public static final RegistryObject<Item> KILL_ZOMBIE;
    public static final RegistryObject<Item> LEVEL_30;
    public static final RegistryObject<Item> MORE_HOOPERS;
    public static final RegistryObject<Item> MORE_KELP;
    public static final RegistryObject<Item> MORE_LEVEL;
    public static final RegistryObject<Item> OPPONENT_HITS_YOU;
    public static final RegistryObject<Item> OPPONENT_TAKES_100_DAMAGE;
    public static final RegistryObject<Item> POISON;
    public static final RegistryObject<Item> SPRINT_1KM;
    public static final RegistryObject<Item> TAKE_200_DAMAGE;
    public static final RegistryObject<Item> USE_CAULDRON;
    public static final RegistryObject<Item> WEAKNESS;

    public ItemInit() {
    }

    static {
        ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, "lockoutbingomod");
        ABSORPTION = ITEMS.register("absorption", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BAD_OMEN = ITEMS.register("bad_omen", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_CHICKEN = ITEMS.register("breed_chicken", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_COW = ITEMS.register("breed_cow", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_HOGLIN = ITEMS.register("breed_hoglin", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_HORSE = ITEMS.register("breed_horse", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_PIG = ITEMS.register("breed_pig", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_SHEEP = ITEMS.register("breed_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_ANVIL = ITEMS.register("die_to_anvil", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_BEE = ITEMS.register("die_to_bee", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_CACTUS = ITEMS.register("die_to_cactus", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_FIREWORK = ITEMS.register("die_to_firework", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_LLAMA = ITEMS.register("die_to_llama", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_MAGIC = ITEMS.register("die_to_magic", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_SWEET_BERRIES = ITEMS.register("die_to_sweet_berries", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        GLOWING = ITEMS.register("glowing", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        HEIGHT_LIMIT = ITEMS.register("height_limit", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        JUMP_BOOST = ITEMS.register("jump_boost", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_GHAST = ITEMS.register("kill_ghast", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_GUARDIAN = ITEMS.register("kill_guardian", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_PLAYER = ITEMS.register("kill_player", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_SILVERFISH = ITEMS.register("kill_silverfish", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_SNOW_GOLEM = ITEMS.register("kill_snow_golem", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_STRAY = ITEMS.register("kill_stray", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_STRAY_CYCLE = ITEMS.register("kill_stray_cycle", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_WITCH = ITEMS.register("kill_witch", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_ZOGLIN = ITEMS.register("kill_zoglin", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_ZOMBIE_VILLAGER = ITEMS.register("kill_zombie_villager", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        LEVITATION = ITEMS.register("levitation", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        MINING_FATIGUE = ITEMS.register("mining_fatigue", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NAUSEA = ITEMS.register("nausea", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NO_CRAFTING_TABLE = ITEMS.register("no_crafting_table", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NO_DEATH = ITEMS.register("no_death", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NO_FALL_DAMAGE = ITEMS.register("no_fall_damage", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NO_FIRE = ITEMS.register("no_fire", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NO_JUMP = ITEMS.register("no_jump", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NO_OBSIDIAN = ITEMS.register("no_obsidian", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NO_SEEDS = ITEMS.register("no_seeds", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NO_WATER = ITEMS.register("no_water", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        STARVE = ITEMS.register("starve", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        TAME_CAT = ITEMS.register("tame_cat", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        TAME_HORSE = ITEMS.register("tame_horse", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        TAME_PARROT = ITEMS.register("tame_parrot", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        TAME_WOLF = ITEMS.register("tame_wolf", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        LEVEL_15 = ITEMS.register("level_15", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        Glow_Crimson_Sign = ITEMS.register("glow_crimson_sign", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        Die_To_Falling_Stalactite = ITEMS.register("die_to_falling_stalactite", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        NETHER_PORTAL = ITEMS.register("nether_portal", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        ADVANCEMENTS_15 = ITEMS.register("15_advancements", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        ADVANCEMENTS_25 = ITEMS.register("25_advancements", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        ADVANCEMENTS_35 = ITEMS.register("35_advancements", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        STATUS_EFFECTS_3 = ITEMS.register("3_status_effects", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        OF_ANYTHING_64 = ITEMS.register("64_of_anything", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        STATUS_EFFECTS_6 = ITEMS.register("6_status_effects", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_FOX = ITEMS.register("breed_fox", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_GOAT = ITEMS.register("breed_goat", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_OCELOT = ITEMS.register("breed_ocelot", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_RABBIT = ITEMS.register("breed_rabbit", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_STRIDER = ITEMS.register("breed_strider", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        BREED_X = ITEMS.register("breed_x", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DEAL_400_DAMAGE = ITEMS.register("deal_400_damage", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_ANCHOR = ITEMS.register("die_to_anchor", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_BED = ITEMS.register("die_to_bed", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_GOLEM = ITEMS.register("die_to_golem", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        DIE_TO_VINES = ITEMS.register("die_to_vines", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        EAT_X_UNIQUE = ITEMS.register("eat_x_unique", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        ENRAGE_ZOMBIE_PIGLIN = ITEMS.register("enrage_zombie_piglin", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_100_MOBS = ITEMS.register("kill_100_mobs", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_BEE_CYCLE = ITEMS.register("kill_bee_cycle", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_BLUE_SHEEP = ITEMS.register("kill_blue_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_CAVE_SPIDER_CYCLE = ITEMS.register("kill_cave_spider_cycle", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_CYAN_SHEEP = ITEMS.register("kill_cyan_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_DROWNED = ITEMS.register("kill_drowned", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_ELDER_GUARDIAN = ITEMS.register("kill_elder_guardian", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_ENDERMITE = ITEMS.register("kill_endermite", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_ENDERMITE_CYCLE = ITEMS.register("kill_endermite_cycle", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_GREEN_SHEEP = ITEMS.register("kill_green_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_HUSK = ITEMS.register("kill_husk", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_LIGHT_BLUE_SHEEP = ITEMS.register("kill_light_blue_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_LIME_SHEEP = ITEMS.register("kill_lime_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_MAGENTA_SHEEP = ITEMS.register("kill_magenta_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_ORANGE_SHEEP = ITEMS.register("kill_orange_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_PINK_SHEEP = ITEMS.register("kill_pink_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_PURPLE_SHEEP = ITEMS.register("kill_purple_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_RED_SHEEP = ITEMS.register("kill_red_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_SILVERFISH_CYCLE = ITEMS.register("kill_silverfish_cycle", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_SPIDER_CYCLE = ITEMS.register("kill_spider_cycle", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_WITHER_SKELETON = ITEMS.register("kill_wither_skeleton", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_X_UNIQUE = ITEMS.register("kill_x_unique", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_YELLOW_SHEEP = ITEMS.register("kill_yellow_sheep", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        KILL_ZOMBIE = ITEMS.register("kill_zombie", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        LEVEL_30 = ITEMS.register("level_30", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        MORE_HOOPERS = ITEMS.register("more_hoopers", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        MORE_KELP = ITEMS.register("more_kelp", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        MORE_LEVEL = ITEMS.register("more_level", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        OPPONENT_HITS_YOU = ITEMS.register("opponent_hits_you", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        OPPONENT_TAKES_100_DAMAGE = ITEMS.register("opponent_takes_100_damage", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        POISON = ITEMS.register("poison", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        SPRINT_1KM = ITEMS.register("sprint_1km", () -> new Item((new Item.Properties()).m_41487_(1100).m_41491_(CreativeModeTab.f_40753_)));
        TAKE_200_DAMAGE = ITEMS.register("take_200_damage", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        USE_CAULDRON = ITEMS.register("use_cauldron", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
        WEAKNESS = ITEMS.register("weakness", () -> new Item((new Item.Properties()).m_41487_(500).m_41491_(CreativeModeTab.f_40753_)));
    }
}
