package com.atsign.lockoutbingomod.core;

import com.atsign.lockoutbingomod.core.LockoutGoal.Tasks;
import java.util.ArrayList;
import java.util.Random;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;

public class LockoutGoals {
    public static ArrayList<LockoutGoal> full_goal_list = new ArrayList();
    public static String[] colors = new String[]{"White", "Orange", "Magenta", "Light Blue", "Yellow", "Lime", "Pink", "Gray", "Light Gray", "Cyan", "Purple", "Blue", "Brown", "Green", "Red", "Black"};
    public static DyeColor[] color_map;
    public static Item[] dye_item_map;
    public static Item[] wool_map;
    public static Item[] concrete_map;
    public static String[] armor_pieces;
    public static Item[] armor_map;

    public LockoutGoals() {
    }

    public static void GenerateGoalList() {
        Random rand = new Random();
        full_goal_list.clear();
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Mine Diamond Ore", Tasks.mine_diamond_ore, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Mine Emerald Ore", Tasks.mine_emerald_ore, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Mine Mob Spawner", Tasks.mine_mob_spawner, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Mine Turtle Egg", Tasks.mine_turtle_egg, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Enter Nether", Tasks.enter_nether, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Enter End", Tasks.enter_end, "", 3)).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill The Ender Dragon", Tasks.kill_ender_dragon, "", 3)).end(1).dragon(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Wooden Tools", Tasks.full_set_wooden_tools, "", 1)).tools(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Stone Tools", Tasks.full_set_stone_tools, "", 1)).tools(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Gold Tools", Tasks.full_set_gold_tools, "", 1)).tools(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Iron Tools", Tasks.full_set_iron_tools, "", 1)).tools(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Diamond Tools", Tasks.full_set_diamond_tools, "", 2)).tools(1).diamond(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Shovel", Tasks.obtain_every_type_of_shovel, "", 3)).tools(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Hoe", Tasks.obtain_every_type_of_hoe, "", 3)).tools(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Axe", Tasks.obtain_every_type_of_axe, "", 3)).tools(1).diamond(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Pickaxe", Tasks.obtain_every_type_of_pickaxe, "", 3)).tools(1).diamond(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Sword", Tasks.obtain_every_type_of_sword, "", 3)).tools(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Fill an Armor Stand with Armor", Tasks.fill_armor_stand, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear Leather Armor Set", Tasks.leather_armor_set, "", 1)).armor(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear Gold Armor Set", Tasks.gold_armor_set, "", 2)).armor(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear Iron Armor Set", Tasks.iron_armor_set, "", 1)).armor(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear Diamond Armor Set", Tasks.diamond_armor_set, "", 3)).armor(1).diamond(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear 1 Piece of Netherite Armor", Tasks.one_piece_netherite_armor, "", 3)).specialarmor(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear 1 Piece of Chain Armor", Tasks.one_piece_chain_armor, "", 3)).specialarmor(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear a carved pumpkin for 5 minutes", Tasks.wear_carved_pumpkin, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Wear %s Colored Leather %s", colors[rand.nextInt(colors.length)], armor_pieces[rand.nextInt(armor_pieces.length)]), Tasks.wear_colored_leather_armor, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Tame a Cat", Tasks.tame_cat, "", 1)).tame(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Tame a Horse", Tasks.tame_horse, "", 1)).tame(1).horse(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Tame a Parrot", Tasks.tame_parrot, "", 1)).tame(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Tame a Wolf", Tasks.tame_wolf, "", 1)).tame(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Cow", Tasks.breed_cow, "", 1)).breed1(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Sheep", Tasks.breed_sheep, "", 1)).breed1(1).sheep(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Chicken", Tasks.breed_chicken, "", 1)).breed1(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Pig", Tasks.breed_pig, "", 1)).breed1(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Horse", Tasks.breed_horse, "", 2)).breed2(1).horse(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Hoglin", Tasks.breed_hoglin, "", 2)).breed2(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Ocelot", Tasks.breed_ocelot, "", 2)).breed2(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Rabbit", Tasks.breed_rabbit, "", 2)).breed1(1).sheep(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Fox", Tasks.breed_fox, "", 2)).breed2(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Strider", Tasks.breed_strider, "", 2)).breed2(1).strider(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Goat", Tasks.breed_goat, "", 1)).breed1(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed 4 Unique Animals", Tasks.breed_4_unique, "", 2)).breedX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed 6 Unique Animals", Tasks.breed_6_unique, "", 2)).breedX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed 8 Unique Animals", Tasks.breed_8_unique, "", 2)).breedX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Witch", Tasks.kill_witch, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Zombie Villager", Tasks.kill_zombie_villager, "", 1)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Stray", Tasks.kill_stray, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Zoglin", Tasks.kill_zoglin, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Silverfish", Tasks.kill_silverfish, "", 3)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Guardian", Tasks.kill_guardian, "", 2)).kill_1_mob(1).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Ghast", Tasks.kill_ghast, "", 1)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Snow Golem", Tasks.kill_snow_golem, "", 1)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Elder Guardian", Tasks.kill_elder_guardian, "", 3)).kill_1_mob(1).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Endermite", Tasks.kill_endermite, "", 3)).kill_1_mob(1).build());

        int rnd;
        for(rnd = 0; rnd == 0 || rnd == 7 || rnd == 8 || rnd == 12 || rnd == 15; rnd = rand.nextInt(colors.length)) {
        }

        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Kill %s Sheep", colors[rnd]), Tasks.kill_colored_sheep, "", 1)).kill_1_mob(1).sheep(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 7 Unique Hostile Mobs", Tasks.kill_7_unique_hostile, "", 2)).kill_x_hostile(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 10 Unique Hostile Mobs", Tasks.kill_10_unique_hostile, "", 2)).kill_x_hostile(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 15 Unique Hostile Mobs", Tasks.kill_15_unique_hostile, "", 3)).kill_x_hostile(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 30 Undead Mobs", Tasks.kill_30_undead, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 20 Arthropods", Tasks.kill_20_arthropods, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill The Other Player", Tasks.kill_the_other_player, "", 2)).player_dies(1).punch(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Red Nether Brick Stairs", Tasks.obtain_red_nether_brick_stairs, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Bucket of Tropical Fish", Tasks.obtain_bucket_of_tropical_fish, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Sea Lantern", Tasks.obtain_sea_lantern, "", 2)).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Bookshelf", Tasks.obtain_bookshelf, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Mossy Stone Brick Wall", Tasks.obtain_mossy_stone_brick_wall, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Flowering Azalea", Tasks.obtain_flowering_azalea, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Scaffolding", Tasks.obtain_scaffolding, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain End Crystal", Tasks.obtain_end_crystal, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Bell", Tasks.obtain_bell, "", 1)).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Bottle o' Enchanting", Tasks.obtain_bottle_o_enchanting, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Slime Block", Tasks.obtain_slime_block, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain a powder snow bucket", Tasks.obtain_a_powder_snow_bucket, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Soul Lantern", Tasks.obtain_soul_lantern, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Honey Bottle", Tasks.obtain_honey_bottle, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Ancient Debris", Tasks.obtain_ancient_debris, "", 3)).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Cake", Tasks.obtain_cake, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Ender Chest", Tasks.obtain_ender_chest, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Heart of the Sea", Tasks.obtain_heart_of_the_sea, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Wither Skeleton Skull", Tasks.obtain_wither_skeleton_skull, "", 3)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Lodestone", Tasks.obtain_lodestone, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain End Rod", Tasks.obtain_end_rod, "", 3)).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Sponge", Tasks.obtain_sponge, "", 2)).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Mushroom Stem", Tasks.obtain_mushroom_stem, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Dragon Egg", Tasks.obtain_dragon_egg, "", 3)).end(1).dragon(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain TNT", Tasks.obtain_tnt, "", 1)).tnt(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Cobweb", Tasks.obtain_cobweb, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Goat Horn", Tasks.obtain_goat_horn, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Mud Brick Wall", Tasks.obtain_mud_brick_wall, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Daylight Detector", Tasks.obtain_daylight_detector, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Redstone Repeater", Tasks.obtain_redstone_repeater, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Redstone Comparator", Tasks.obtain_redstone_comparator, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Observer", Tasks.obtain_observer, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Activator Rail", Tasks.obtain_activator_rail, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Detector Rail", Tasks.obtain_detector_rail, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Powered Rail", Tasks.obtain_powered_rail, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Dispenser", Tasks.obtain_dispenser, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Piston", Tasks.obtain_piston, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Raw Ore Block", Tasks.obtain_every_type_of_raw_ore, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain 5 Types of Saplings", Tasks.obtain_every_type_of_sapling, "", 2)).collect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain every type of horse armor", Tasks.obtain_every_type_horse_armor, "", 2)).fortress(1).collect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Seed", Tasks.obtain_every_type_of_seed, "", 2)).collect(1).seed(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain 6 Unique Flowers", Tasks.obtain_6_unique_flowers, "", 2)).collect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Obtain %s Glazed Terracotta", colors[rand.nextInt(colors.length)]), Tasks.obtain_glazed_terracotta, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain 64 of Any One Item/Block", Tasks.obtain_64_of_one_item_block, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Obtain 64 %s Wool", colors[rand.nextInt(colors.length)]), Tasks.obtain_64_x_wool, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Obtain 64 %s Concrete", colors[rand.nextInt(colors.length)]), Tasks.obtain_64_x_concrete, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Write a Book", Tasks.write_book, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Fill Inventory with Unique Items", Tasks.fill_inventory_with_unique_items, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get \"This Boat Has Legs\" Advancement", Tasks.this_boat_has_legs_strider, "", 2)).ride(1).strider(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Ride Pig with a Carrot on a Stick", Tasks.ride_pig_with_carrot_on_stick, "", 2)).ride(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Ride Horse with a Saddle", Tasks.ride_horse_with_saddle, "", 2)).ride(1).horse(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Ride Minecart", Tasks.ride_minecart, "", 1)).ride(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Brewing Stand", Tasks.use_a_brewing_stand, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Healing", Tasks.brew_potion_of_healing, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Leaping", Tasks.brew_potion_of_leaping, "", 3)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Swiftness", Tasks.brew_potion_of_swiftness, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Invisibility", Tasks.brew_potion_of_invisibility, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Water Breathing", Tasks.brew_potion_of_water_breathing, "", 1)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Lingering", Tasks.brew_potion_of_lingering, "", 3)).fortress(1).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Pumpkin Pie", Tasks.eat_pumpkin_pie, "", 2)).eat(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat a glow berry", Tasks.eat_a_glow_berry, "", 2)).eat(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Rabbit Stew", Tasks.eat_rabbit_stew, "", 2)).eat(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Suspicious Stew", Tasks.eat_suspicious_stew, "", 1)).eat(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Cookie", Tasks.eat_cookie, "", 2)).eat(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Chorus Fruit", Tasks.eat_chorus_fruit, "", 3)).eat(1).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Poisonous Potato", Tasks.eat_poisonous_potato, "", 1)).eat(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat 5 Unique Foods", Tasks.eat_5_unique_food, "", 2)).eatX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat 10 Unique Foods", Tasks.eat_10_unique_food, "", 2)).eatX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat 20 Unique Foods", Tasks.eat_20_unique_food, "", 3)).eatX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Nausea", Tasks.get_nausea, "", 2)).effect(1).poison(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Jump Boost", Tasks.get_jump_boost, "", 1)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Absorption", Tasks.get_absorption, "", 1)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Levitation", Tasks.get_levitation, "", 3)).effect(1).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Glowing", Tasks.get_glowing, "", 2)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Mining Fatigue", Tasks.get_mining_fatigue, "", 2)).effect(1).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Bad Omen", Tasks.get_bad_omen, "", 2)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Weakness", Tasks.get_weakness, "", 1)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Poisoned", Tasks.get_poisoned, "", 1)).effect(1).poison(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 3 Status Effects at Once", Tasks.get_3_status_effects_at_once, "", 2)).poison(1).effectX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 6 Status Effects at Once", Tasks.get_6_status_effects_at_once, "", 3)).effectX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Remove a Status Effect with a Milk Bucket", Tasks.remove_status_effect_with_milk, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Bee Sting", Tasks.die_by_bee_sting, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Llama", Tasks.die_by_llama, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Cactus", Tasks.die_by_cactus, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Berry Bush", Tasks.die_by_berry_bush, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Anvil", Tasks.die_by_anvil, "", 2)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Firework Rocket", Tasks.die_by_firework_rocket, "", 2)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die to Falling Stalactite", Tasks.die_to_falling_stalactite, "", 2)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Magic", Tasks.die_by_magic, "", 3)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die to Iron Golem", Tasks.die_to_iron_golem, "", 1)).die(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die to [Intentional Game Design]", Tasks.die_to_intentional_game_design, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Falling Off Vines", Tasks.die_by_falling_off_vines, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find an Ice Spike Biome", Tasks.find_ice_spike_biome, "", 3)).biome(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Mushroom Biome", Tasks.find_mushroom_biome, "", 3)).biome(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Badlands Biome", Tasks.find_badlands_biome, "", 3)).biome(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Fortress", Tasks.find_fortress, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Bastion", Tasks.find_bastion, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Stronghold", Tasks.find_stronghold, "", 3)).end_structure(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find an End City", Tasks.find_end_city, "", 3)).end_structure(1).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Smithing Table", Tasks.use_smithing_table, "", 3)).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use an Enchanting Table", Tasks.use_enchanting_table, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use an Anvil", Tasks.use_anvil, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Composter", Tasks.use_composter, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Cauldron to wash something", Tasks.use_cauldron_to_wash, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Loom to Design a Banner", Tasks.use_loom_to_design_banner, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Jukebox to play a Music Disc", Tasks.use_jukebox_to_play_music, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Dies", Tasks.opponent_dies, "", 2)).die(3).player_dies(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Dies 3 Times", Tasks.opponent_dies_3_times, "", 2)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Catches on Fire", Tasks.opponent_catches_fire, "", 2)).opponenent_hurts(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Obtains a Crafting Table", Tasks.opponent_obtains_crafting_table, "", 2)).opponent_hard(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Obtains Obsidian", Tasks.oponnent_obtains_obsidian, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Obtains Seeds", Tasks.oponnent_obtains_seeds, "", 2)).seed(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Jumps", Tasks.opponent_jumps, "", 2)).opponent_hard(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Touches Water", Tasks.opponent_touches_water, "", 2)).opponent_hard(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Takes Fall Damage", Tasks.opponent_takes_fall_damage, "", 2)).opponenent_hurts(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Takes 100 Total Damage", Tasks.opponent_takes_100_total_damage, "", 2)).damage(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent is hit by a Snowball", Tasks.opponent_is_hit_by_snowball, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Hits You", Tasks.opponent_hits_you, "", 1)).punch(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Sleep Alone in the Overworld", Tasks.sleep_alone_in_overworld, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Spawn a Chicken with an Egg", Tasks.spawn_a_chicken_with_an_egg, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Reach Level 15", Tasks.reach_level_15, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Reach Level 30", Tasks.reach_level_30, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use glow ink on a crimson sign", Tasks.use_glow_ink_on_crimson_sign, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Empty Hunger Bar", Tasks.empty_huger_bar, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Reach Bedrock", Tasks.reach_bedrock, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Reach Sky Limit", Tasks.reach_sky_limit, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die to TNT Minecart", Tasks.detonate_tnt_minecart, "", 1)).tnt(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Enrage a Zombie Piglin", Tasks.enrage_zombie_piglin, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Take 200 Damage", Tasks.take_200_damage, "", 2)).damage(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 100 Mobs", Tasks.kill_100_mobs, "", 2)).kill100(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Deal 400 Damage", Tasks.deal_400_damage, "", 2)).kill100(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Sprint 1km", Tasks.sprint_1k, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get any Spyglass Advancement", Tasks.get_any_spyglass_advancement, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Trade with a Villager", Tasks.trade_with_villager, "", 1)).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Distract a Piglin with Gold", Tasks.distract_piglin, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Visit All Nether Biomes", Tasks.visit_all_nether_biomes, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get \"Sniper Duel\" Advancement", Tasks.get_sniper_duel, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get \"Bullseye\" Advancement", Tasks.get_bullseye, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Charge a Respawn Anchor to Max", Tasks.charge_respawn_anchor_to_max, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 15 Advancements", Tasks.get_15_advancements, "", 1)).advancement(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 25 Advancements", Tasks.get_25_advancements, "", 2)).advancement(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 35 Advancements", Tasks.get_35_advancements, "", 3)).advancement(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain More Dried Kelp Blocks than the Opponent", Tasks.obtain_more_dried_kelp_than_opponent, "", 1)).obtain_more(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain More Hoppers than the opponent", Tasks.obtain_more_hoppers_than_opponent, "", 2)).obtain_more(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Have More Levels than the opponent", Tasks.have_more_levels_than_opponent, "", 3)).obtain_more(1).build());
    }

    public static void GenerateFullGoalList() {
        full_goal_list.clear();
        full_goal_list.clear();
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Mine Diamond Ore", Tasks.mine_diamond_ore, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Mine Emerald Ore", Tasks.mine_emerald_ore, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Mine Mob Spawner", Tasks.mine_mob_spawner, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Mine Turtle Egg", Tasks.mine_turtle_egg, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Enter Nether", Tasks.enter_nether, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Enter End", Tasks.enter_end, "", 3)).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill The Ender Dragon", Tasks.kill_ender_dragon, "", 3)).end(1).dragon(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Wooden Tools", Tasks.full_set_wooden_tools, "", 1)).tools(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Stone Tools", Tasks.full_set_stone_tools, "", 1)).tools(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Gold Tools", Tasks.full_set_gold_tools, "", 1)).tools(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Iron Tools", Tasks.full_set_iron_tools, "", 1)).tools(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Full Set of Diamond Tools", Tasks.full_set_diamond_tools, "", 2)).tools(1).diamond(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Shovel", Tasks.obtain_every_type_of_shovel, "", 3)).tools(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Hoe", Tasks.obtain_every_type_of_hoe, "", 3)).tools(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Axe", Tasks.obtain_every_type_of_axe, "", 3)).tools(1).diamond(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Pickaxe", Tasks.obtain_every_type_of_pickaxe, "", 3)).tools(1).diamond(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Sword", Tasks.obtain_every_type_of_sword, "", 3)).tools(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Fill an Armor Stand with Armor", Tasks.fill_armor_stand, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear Leather Armor Set", Tasks.leather_armor_set, "", 1)).armor(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear Gold Armor Set", Tasks.gold_armor_set, "", 2)).armor(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear Iron Armor Set", Tasks.iron_armor_set, "", 1)).armor(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear Diamond Armor Set", Tasks.diamond_armor_set, "", 3)).armor(1).diamond(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear 1 Piece of Netherite Armor", Tasks.one_piece_netherite_armor, "", 3)).specialarmor(1).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear 1 Piece of Chain Armor", Tasks.one_piece_chain_armor, "", 3)).specialarmor(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Wear a carved pumpkin for 5 minutes", Tasks.wear_carved_pumpkin, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Tame a Cat", Tasks.tame_cat, "", 1)).tame(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Tame a Horse", Tasks.tame_horse, "", 1)).tame(1).horse(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Tame a Parrot", Tasks.tame_parrot, "", 1)).tame(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Tame a Wolf", Tasks.tame_wolf, "", 1)).tame(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Cow", Tasks.breed_cow, "", 1)).breed1(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Sheep", Tasks.breed_sheep, "", 1)).breed1(1).sheep(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Chicken", Tasks.breed_chicken, "", 1)).breed1(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Pig", Tasks.breed_pig, "", 1)).breed1(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Horse", Tasks.breed_horse, "", 2)).breed2(1).horse(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Hoglin", Tasks.breed_hoglin, "", 2)).breed2(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Ocelot", Tasks.breed_ocelot, "", 2)).breed2(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Rabbit", Tasks.breed_rabbit, "", 2)).breed1(1).sheep(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Fox", Tasks.breed_fox, "", 2)).breed2(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Strider", Tasks.breed_strider, "", 2)).breed2(1).strider(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed Goat", Tasks.breed_goat, "", 1)).breed1(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed 4 Unique Animals", Tasks.breed_4_unique, "", 2)).breedX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed 6 Unique Animals", Tasks.breed_6_unique, "", 2)).breedX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Breed 8 Unique Animals", Tasks.breed_8_unique, "", 2)).breedX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Witch", Tasks.kill_witch, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Zombie Villager", Tasks.kill_zombie_villager, "", 1)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Stray", Tasks.kill_stray, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Zoglin", Tasks.kill_zoglin, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Silverfish", Tasks.kill_silverfish, "", 3)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Guardian", Tasks.kill_guardian, "", 2)).kill_1_mob(1).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Ghast", Tasks.kill_ghast, "", 1)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Snow Golem", Tasks.kill_snow_golem, "", 1)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Elder Guardian", Tasks.kill_elder_guardian, "", 3)).kill_1_mob(1).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill Endermite", Tasks.kill_endermite, "", 3)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 7 Unique Hostile Mobs", Tasks.kill_7_unique_hostile, "", 2)).kill_x_hostile(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 10 Unique Hostile Mobs", Tasks.kill_10_unique_hostile, "", 2)).kill_x_hostile(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 15 Unique Hostile Mobs", Tasks.kill_15_unique_hostile, "", 3)).kill_x_hostile(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 30 Undead Mobs", Tasks.kill_30_undead, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 20 Arthropods", Tasks.kill_20_arthropods, "", 2)).kill_1_mob(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill The Other Player", Tasks.kill_the_other_player, "", 2)).player_dies(1).punch(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Red Nether Brick Stairs", Tasks.obtain_red_nether_brick_stairs, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Bucket of Tropical Fish", Tasks.obtain_bucket_of_tropical_fish, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Sea Lantern", Tasks.obtain_sea_lantern, "", 2)).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Bookshelf", Tasks.obtain_bookshelf, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Mossy Stone Brick Wall", Tasks.obtain_mossy_stone_brick_wall, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Flowering Azalea", Tasks.obtain_flowering_azalea, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Scaffolding", Tasks.obtain_scaffolding, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain End Crystal", Tasks.obtain_end_crystal, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Bell", Tasks.obtain_bell, "", 1)).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Bottle o' Enchanting", Tasks.obtain_bottle_o_enchanting, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Slime Block", Tasks.obtain_slime_block, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain a powder snow bucket", Tasks.obtain_a_powder_snow_bucket, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Soul Lantern", Tasks.obtain_soul_lantern, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Honey Bottle", Tasks.obtain_honey_bottle, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Ancient Debris", Tasks.obtain_ancient_debris, "", 3)).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Cake", Tasks.obtain_cake, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Ender Chest", Tasks.obtain_ender_chest, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Heart of the Sea", Tasks.obtain_heart_of_the_sea, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Wither Skeleton Skull", Tasks.obtain_wither_skeleton_skull, "", 3)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Lodestone", Tasks.obtain_lodestone, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain End Rod", Tasks.obtain_end_rod, "", 3)).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Sponge", Tasks.obtain_sponge, "", 2)).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Mushroom Stem", Tasks.obtain_mushroom_stem, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Dragon Egg", Tasks.obtain_dragon_egg, "", 3)).end(1).dragon(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain TNT", Tasks.obtain_tnt, "", 1)).tnt(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Cobweb", Tasks.obtain_cobweb, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Goat Horn", Tasks.obtain_goat_horn, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Mud Brick Wall", Tasks.obtain_mud_brick_wall, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Daylight Detector", Tasks.obtain_daylight_detector, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Redstone Repeater", Tasks.obtain_redstone_repeater, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Redstone Comparator", Tasks.obtain_redstone_comparator, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Observer", Tasks.obtain_observer, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Activator Rail", Tasks.obtain_activator_rail, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Detector Rail", Tasks.obtain_detector_rail, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Powered Rail", Tasks.obtain_powered_rail, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Dispenser", Tasks.obtain_dispenser, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Piston", Tasks.obtain_piston, "", 1)).redstone(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Raw Ore Block", Tasks.obtain_every_type_of_raw_ore, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain 5 Types of Saplings", Tasks.obtain_every_type_of_sapling, "", 2)).collect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain every type of horse armor", Tasks.obtain_every_type_horse_armor, "", 2)).fortress(1).collect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain Every Type of Seed", Tasks.obtain_every_type_of_seed, "", 2)).collect(1).seed(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain 6 Unique Flowers", Tasks.obtain_6_unique_flowers, "", 2)).collect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain 64 of Any One Item/Block", Tasks.obtain_64_of_one_item_block, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Write a Book", Tasks.write_book, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Fill Inventory with Unique Items", Tasks.fill_inventory_with_unique_items, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get \"This Boat Has Legs\" Advancement", Tasks.this_boat_has_legs_strider, "", 2)).ride(1).strider(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Ride Pig with a Carrot on a Stick", Tasks.ride_pig_with_carrot_on_stick, "", 2)).ride(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Ride Horse with a Saddle", Tasks.ride_horse_with_saddle, "", 2)).ride(1).horse(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Ride Minecart", Tasks.ride_minecart, "", 1)).ride(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Brewing Stand", Tasks.use_a_brewing_stand, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Healing", Tasks.brew_potion_of_healing, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Leaping", Tasks.brew_potion_of_leaping, "", 3)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Swiftness", Tasks.brew_potion_of_swiftness, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Invisibility", Tasks.brew_potion_of_invisibility, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Water Breathing", Tasks.brew_potion_of_water_breathing, "", 1)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Brew Potion of Lingering", Tasks.brew_potion_of_lingering, "", 3)).fortress(1).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Pumpkin Pie", Tasks.eat_pumpkin_pie, "", 2)).eat(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat a glow berry", Tasks.eat_a_glow_berry, "", 2)).eat(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Rabbit Stew", Tasks.eat_rabbit_stew, "", 2)).eat(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Suspicious Stew", Tasks.eat_suspicious_stew, "", 1)).eat(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Cookie", Tasks.eat_cookie, "", 2)).eat(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Chorus Fruit", Tasks.eat_chorus_fruit, "", 3)).eat(1).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat Poisonous Potato", Tasks.eat_poisonous_potato, "", 1)).eat(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat 5 Unique Foods", Tasks.eat_5_unique_food, "", 2)).eatX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat 10 Unique Foods", Tasks.eat_10_unique_food, "", 2)).eatX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Eat 20 Unique Foods", Tasks.eat_20_unique_food, "", 3)).eatX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Nausea", Tasks.get_nausea, "", 2)).effect(1).poison(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Jump Boost", Tasks.get_jump_boost, "", 1)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Absorption", Tasks.get_absorption, "", 1)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Levitation", Tasks.get_levitation, "", 3)).effect(1).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Glowing", Tasks.get_glowing, "", 2)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Mining Fatigue", Tasks.get_mining_fatigue, "", 2)).effect(1).monument(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Bad Omen", Tasks.get_bad_omen, "", 2)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Weakness", Tasks.get_weakness, "", 1)).effect(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get Poisoned", Tasks.get_poisoned, "", 1)).effect(1).poison(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 3 Status Effects at Once", Tasks.get_3_status_effects_at_once, "", 2)).poison(1).effectX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 6 Status Effects at Once", Tasks.get_6_status_effects_at_once, "", 3)).effectX(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Remove a Status Effect with a Milk Bucket", Tasks.remove_status_effect_with_milk, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Bee Sting", Tasks.die_by_bee_sting, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Llama", Tasks.die_by_llama, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Cactus", Tasks.die_by_cactus, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Berry Bush", Tasks.die_by_berry_bush, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Anvil", Tasks.die_by_anvil, "", 2)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Firework Rocket", Tasks.die_by_firework_rocket, "", 2)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die to Falling Stalactite", Tasks.die_to_falling_stalactite, "", 2)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Magic", Tasks.die_by_magic, "", 3)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die to Iron Golem", Tasks.die_to_iron_golem, "", 1)).die(1).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die to [Intentional Game Design]", Tasks.die_to_intentional_game_design, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die by Falling Off Vines", Tasks.die_by_falling_off_vines, "", 1)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find an Ice Spike Biome", Tasks.find_ice_spike_biome, "", 3)).biome(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Mushroom Biome", Tasks.find_mushroom_biome, "", 3)).biome(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Badlands Biome", Tasks.find_badlands_biome, "", 3)).biome(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Fortress", Tasks.find_fortress, "", 2)).fortress(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Bastion", Tasks.find_bastion, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find a Stronghold", Tasks.find_stronghold, "", 3)).end_structure(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Find an End City", Tasks.find_end_city, "", 3)).end_structure(1).end(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Smithing Table", Tasks.use_smithing_table, "", 3)).netherite(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use an Enchanting Table", Tasks.use_enchanting_table, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use an Anvil", Tasks.use_anvil, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Composter", Tasks.use_composter, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Cauldron to wash something", Tasks.use_cauldron_to_wash, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Loom to Design a Banner", Tasks.use_loom_to_design_banner, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use a Jukebox to play a Music Disc", Tasks.use_jukebox_to_play_music, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Dies", Tasks.opponent_dies, "", 2)).die(3).player_dies(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Dies 3 Times", Tasks.opponent_dies_3_times, "", 2)).die(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Catches on Fire", Tasks.opponent_catches_fire, "", 2)).opponenent_hurts(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Obtains a Crafting Table", Tasks.opponent_obtains_crafting_table, "", 2)).opponent_hard(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Obtains Obsidian", Tasks.oponnent_obtains_obsidian, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Obtains Seeds", Tasks.oponnent_obtains_seeds, "", 2)).seed(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Jumps", Tasks.opponent_jumps, "", 2)).opponent_hard(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Touches Water", Tasks.opponent_touches_water, "", 2)).opponent_hard(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Takes Fall Damage", Tasks.opponent_takes_fall_damage, "", 2)).opponenent_hurts(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Takes 100 Total Damage", Tasks.opponent_takes_100_total_damage, "", 2)).damage(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent is hit by a Snowball", Tasks.opponent_is_hit_by_snowball, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("An Opponent Hits You", Tasks.opponent_hits_you, "", 1)).punch(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Sleep Alone in the Overworld", Tasks.sleep_alone_in_overworld, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Spawn a Chicken with an Egg", Tasks.spawn_a_chicken_with_an_egg, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Reach Level 15", Tasks.reach_level_15, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Reach Level 30", Tasks.reach_level_30, "", 3)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Use glow ink on a crimson sign", Tasks.use_glow_ink_on_crimson_sign, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Empty Hunger Bar", Tasks.empty_huger_bar, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Reach Bedrock", Tasks.reach_bedrock, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Reach Sky Limit", Tasks.reach_sky_limit, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Die to TNT Minecart", Tasks.detonate_tnt_minecart, "", 1)).tnt(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Enrage a Zombie Piglin", Tasks.enrage_zombie_piglin, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Take 200 Damage", Tasks.take_200_damage, "", 2)).damage(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Kill 100 Mobs", Tasks.kill_100_mobs, "", 2)).kill100(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Deal 400 Damage", Tasks.deal_400_damage, "", 2)).kill100(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Sprint 1km", Tasks.sprint_1k, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get any Spyglass Advancement", Tasks.get_any_spyglass_advancement, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Trade with a Villager", Tasks.trade_with_villager, "", 1)).village(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Distract a Piglin with Gold", Tasks.distract_piglin, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Visit All Nether Biomes", Tasks.visit_all_nether_biomes, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get \"Sniper Duel\" Advancement", Tasks.get_sniper_duel, "", 1)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get \"Bullseye\" Advancement", Tasks.get_bullseye, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Charge a Respawn Anchor to Max", Tasks.charge_respawn_anchor_to_max, "", 2)).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 15 Advancements", Tasks.get_15_advancements, "", 1)).advancement(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 25 Advancements", Tasks.get_25_advancements, "", 2)).advancement(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Get 35 Advancements", Tasks.get_35_advancements, "", 3)).advancement(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain More Dried Kelp Blocks than the Opponent", Tasks.obtain_more_dried_kelp_than_opponent, "", 1)).obtain_more(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Obtain More Hoppers than the opponent", Tasks.obtain_more_hoppers_than_opponent, "", 2)).obtain_more(1).build());
        full_goal_list.add((new LockoutGoal.LockoutGoalBuilder("Have More Levels than the opponent", Tasks.have_more_levels_than_opponent, "", 3)).obtain_more(1).build());

        for(String color : colors) {
            full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Kill %s Sheep", color), Tasks.kill_colored_sheep, "", 1)).kill_1_mob(1).sheep(1).build());
            full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Obtain %s Glazed Terracotta", color), Tasks.obtain_glazed_terracotta, "", 1)).build());
            full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Obtain 64 %s Wool", color), Tasks.obtain_64_x_wool, "", 2)).build());
            full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Obtain 64 %s Concrete", color), Tasks.obtain_64_x_concrete, "", 2)).build());

            for(String armor_piece : armor_pieces) {
                full_goal_list.add((new LockoutGoal.LockoutGoalBuilder(String.format("Wear %s Colored Leather %s", color, armor_piece), Tasks.wear_colored_leather_armor, "", 1)).build());
            }
        }

    }

    static {
        color_map = new DyeColor[]{DyeColor.WHITE, DyeColor.ORANGE, DyeColor.MAGENTA, DyeColor.LIGHT_BLUE, DyeColor.YELLOW, DyeColor.LIME, DyeColor.PINK, DyeColor.GRAY, DyeColor.LIGHT_GRAY, DyeColor.CYAN, DyeColor.PURPLE, DyeColor.BLUE, DyeColor.BROWN, DyeColor.GREEN, DyeColor.RED, DyeColor.BLACK};
        dye_item_map = new Item[]{Items.f_42535_, Items.f_42536_, Items.f_42537_, Items.f_42538_, Items.f_42539_, Items.f_42540_, Items.f_42489_, Items.f_42490_, Items.f_42491_, Items.f_42492_, Items.f_42493_, Items.f_42494_, Items.f_42495_, Items.f_42496_, Items.f_42497_, Items.f_42498_};
        wool_map = new Item[]{Items.f_41870_, Items.f_41871_, Items.f_41872_, Items.f_41873_, Items.f_41874_, Items.f_41875_, Items.f_41876_, Items.f_41877_, Items.f_41878_, Items.f_41932_, Items.f_41933_, Items.f_41934_, Items.f_41935_, Items.f_41936_, Items.f_41937_, Items.f_41938_};
        concrete_map = new Item[]{Items.f_42246_, Items.f_42247_, Items.f_42248_, Items.f_42249_, Items.f_42303_, Items.f_42304_, Items.f_42305_, Items.f_42306_, Items.f_42307_, Items.f_42308_, Items.f_42309_, Items.f_42310_, Items.f_42311_, Items.f_42312_, Items.f_42313_, Items.f_42314_};
        armor_pieces = new String[]{"Helmet", "Chestplate", "Leggings", "Boots"};
        armor_map = new Item[]{Items.f_42407_, Items.f_42408_, Items.f_42462_, Items.f_42463_};
    }
}
